### ISSUE TITLE
More detailed documentation / tutorial

### ISSUE THREAD

**Issue by asyncee** [prkumar/uplink#19]
Hello, thank you for such a great library.

Can you write documentation or tutorials in retrofit-like way?

http://square.github.io/retrofit/

## TODO (added by @prkumar):
- [x] Add [scripts from gist](https://gist.github.com/prkumar/4e905edb988bc3d3d95e680ef043f934) to `examples/` (see #35)
- [x] Add example with `marshmallow`
- [x] Add README under `examples/`, including relevant info, such as a brief summary for each example.
- [x] Consider rewriting root ``README.rst`` and/or documentation home page. An options is to adopt the tutorial structure used in [Retrofit's landing page](http://square.github.io/retrofit/).

**Comment by prkumar** [comment]
Sounds like a reasonable request! Let's get on it!

For what it's worth, there's some extensive documentation in the getting started guide: https://uplink.readthedocs.io/en/latest/getting_started.html.  But, it would also be nice to have some more concise and accessible tutorials, and maybe place one in the README or the landing page of the documentation.

**Comment by prkumar** [comment]
Reopening this issue as there's still more work to do!

**Comment by prkumar** [comment]
TODO:
- [ ] Add [scripts from gist](https://gist.github.com/prkumar/4e905edb988bc3d3d95e680ef043f934) to `examples/`

**Comment by prkumar** [comment]
## TODO:
- [ ] Add [scripts from gist](https://gist.github.com/prkumar/4e905edb988bc3d3d95e680ef043f934) to `examples/`
- [ ] Consider rewriting ``README.rst`` and/or documentation home page. An options is to adopt the tutorial structure used in [Retrofit's landing page](http://square.github.io/retrofit/).
