### ISSUE TITLE
Add documentation for v0.4 features

### ISSUE THREAD

**Issue by prkumar** [prkumar/uplink#66]
Here are a some  v0.4 features that may be missing documentation:
- [ ] Basic Auth support (#58)
- [ ] Registering response handlers (#62)
- [ ] Registering error handlers (#63)
- [ ] Set request properties from constructor arguments (#65)
- [ ] Added `Consumer._inject` method and `inject` decorator (#67)
